### ISSUE TITLE
Add examples implementing different PPL styles with Funsor backend

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#121]
@lawmurray suggested adding examples of how to implement different styles of probabilistic programming languages on top of Funsor. We could implement this as a directory examples/ppl-zoo or examples/rosetta or something.

## Tasks
(@eb8680 @lawmurray I've tried to populate with representative examples, but I think you both have clearer views of the landscape; feel free to update/add to/remove from this list)

- [x] add a Pyro example (minipyro)
- [ ] add a Birch-style example (with delayed sampling, maybe using `pyro.ground`)
- [ ] add a Stan-style example (constructing a non-normalized log-density function)
- [ ] add a Venture-style example
- [ ] Add an Infer.net-style example
- [ ] Add a Church-style example
