### ISSUE TITLE
Clean up substitution

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/funsor#149]
#148 introduces several major changes to substitution as part of the implementation of alpha-conversion.  These changes should allow us to further simplify a lot of the old substitution logic:
- [x] #152 Remove `eager_subs` methods from all terms (e.g. `Binary`, `Joint`) that do not introduce fresh variables
- [x] #152 Remove conditional xfails and extra test runs added temporarily as part of #148 
- [x] #153 Factor out non-fresh substitution logic from remaining `eager_subs` methods (e.g in `Delta`) so that terms only have to be responsible for substituting into their fresh variables
- [x] #153 Make `Subs` compatible with `FUNSOR_DEBUG=1` again
- [x] #154 Update `Joint` and associated patterns so that `Joint.eager_subs` can be removed
- [ ] #155 Make the new `substitute` function into an interpreter, allowing tail-call optimized substitution via #145
