### ISSUE TITLE
Project: Implement time series models usable in Pyro

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#177]
This issue plans PRs required to implement Bayesian filtering models in funsor that can then be used within Pyro models. We'd like to include a number of these in the initial release.

## Low level algorithms and math
- [x] #161  Implement `sequential_sum_product()` for discrete HMMs
- [x] #176 Implement `sequential_sum_product()` for Gaussian HMMs
- [x] #183 Support multiple variables in `sequential_sum_product()`
- [x] #173 Support multivariate linear pattern matching for linear-Gaussian filtering
- [x] #178 Implement partial substitution of Gaussian funsors 
- [x] #186 #184 Support rank-deficient operands in Gaussians ops
- ~~Implement a "Gaussian GEMM" that avoids the broadcast-multiply-reduce pattern (see `pyro.ops.gaussian.gaussian_tensordot()` https://github.com/pyro-ppl/pyro/pull/1980)~~ moved to https://github.com/pyro-ppl/funsor/issues/238
- ~~#167 Implement a `markov_sum_product()` for structured HMMs with arbitrary time window~~

## High level components
- [x] #170 Implement a `FunsorDistribution` wrapper to embed funsor distributions in Pyro
- [x] #174 #175 Implement funsor-pyro conversion functions
- [x] #205 Promote `funsor.sum_product.Slice` from an ad-hoc function to a `Funsor`
- [x] #206 Implement `eager_cat` for `Tensor`, `Gaussian`, `Joint` (cross listed in #162)
- ~~#70 Add a `Markov` or `Convolve` funsor~~

## Models as distributions
- [x] #171 Implement `DiscreteHMM` as a `FunsorDistribution`
- [x] #179 Implement a `GaussianMRF`
- [x] #185 Implement a `GaussianHMM`
- ~~#182 Implement a `GaussianDiscreteMRF`~~
- ~~#180 Implement a switching linear dynamical system MRF~~
- [x]  #187 Implement a switching linear dynamical system HMM
- ~~Implement a Tensor Monte Carlo smoothing `FunsorDistribution`~~
