### ISSUE TITLE
Fix docs for initial release

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#201]
## Tasks
- [x] #200 Fix readthedocs build
- [x] #202 ensure all modules appear in index.rst
- [x] #277 add docstrings to funsor.pyro.hmm
- [x] #280 ensure all user-facing Funsor constructors are documented (i.e. with `:param: ...`)
- [ ] #283 update README.md, especially the section on organization

## Triaged
- work around lack of support for default options (commented out in #200)
