### ISSUE TITLE
FR: syntactic sugar and API tweaks

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/funsor#211]
- [x] #218 wrap passed args in `frozenset` under the hood so i can write `log_prob.reduce(ops.logaddexp, {a, b})` instead of `log_prob.reduce(ops.logaddexp, frozenset([a, b]))` ?
- [x] #276 similarly support passing in `funsor.Variable`s into `reduce` so i can write `log_prob.reduce(ops.logaddexp, frozenset([var_a, var_b]))` instead of `log_prob.reduce(ops.logaddexp, frozenset([var_a.name, var_b.name]))` ?
- [x] #276 support passing str and set args to `Integrate`, just like `.reduce()`.

## Triaged
- some of the funsor conversion methods, e.g. `matrix_and_mvn_to_funsor`, should probably error if passed spurious `event_dims`; c.f. [slds example](https://github.com/pyro-ppl/funsor/blob/fcc9a0e90b65f3a17ea243a16acf29fddab24336/examples/eeg_slds.py#L97)
  - let's revisit this as we see more usage patterns. In the long term we may deprecate these methods in favor of Gaussian-affine pattern matching anyway. -@fritzo
