### ISSUE TITLE
Implement Align and .align() funsors

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#26]
We should resurrect [.align()](https://github.com/pyro-ppl/funsor/blob/da322019d355bd43d564a6b5b42c65402b2df064/funsor/terms.py#L105) and [Align](https://github.com/pyro-ppl/funsor/blob/da322019d355bd43d564a6b5b42c65402b2df064/funsor/terms.py#L388), which were deleted during the v3 refactoring #17. 

These are convenience funsors so that e.g. we can define
```py
@funsor.of_shape(reals(), reals(), reals())
def normal(loc, scale, value):
    return -((value - loc) ** 2) / (2 * scale ** 2) - scale.log() -
        math.log(math.sqrt(2 * math.pi))
```
and ensure its inputs are ordered `(loc, scale, value)` rather than `(value, loc, scale)`.

## Tasks

First PR:
- [x] Implement a simple `Align` to simply re-order its inputs.
- [x] `Align.eager_*()` methods do not need to preserve alignment; they can simply defer to `self.arg.eager_*()`.
- [x] Make `Funsor.align()` call `Align`
- [x] Use `.align()` in `of_funsor`
- [x] Add `Funsor.align()` tests to test_terms.py

Second PR:
- [x] Make `Tensor.align()` call `torch.permute()` under the hood
- [x] Add `Tensor.align()` tests to test_torch.py

**Comment by fritzo** [comment]
@jpchen This would be a nice first issue to work on
