### ISSUE TITLE
Remove Substute; make all Funsors closed under substitution

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#27]
## Tasks

- [x] ~~#28~~ #29 Make `Function` closed under substitution
- [x] #29 Remove `Substitute` (requires refactoring `.eager_subs()` methods)
- [ ] #33 Make `Tensor` closed under substitution (and disallow real `inputs` #29)
- [ ] Make `Stack`/`Branch`/`Switch` closed under substitution

**Comment by fritzo** [comment]
It appears that lazy substitution can simplify distribution code and allow e.g. transformed distributions and factorial distributions.
