### ISSUE TITLE
Add generalized parallel-scan algorithms for dynamic factor graphs

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/funsor#293]
Tasks:
- [x] #292 Implement parallel-scan `sarkka_bilmes_product` operation
- [ ] Support global variables, either by passing a `global_vars` argument or following the subscripting design of #167 and assuming non-subscripted variables are global by default
- [ ] Handle partial windows
- [ ] Update interface to follow the subscripting design in #167 
- [ ] Change function name to something more descriptive
- [ ] Add Gaussian tests
- [ ] Add `moment_matching` tests
- [ ] Promote `sarkka_bilmes_product` to a first-class Funsor, like `MarkovProduct`
- [ ] Add docs defining the operation and explaining the parallelism-memory tradeoff for both `naive_sarkka_bilmes_product` and `sarkka_bilmes_product`
- [ ] Add some examples
- [ ] Generalize `partial_sum_product` to call `MarkovProduct`

**Comment by eb8680** [comment]
@ordabayevy I copied the work plan from #398 to this issue.  I suggest going ahead with making `modified_partial_sum_product` use the first-class Funsor `funsor.sum_product.MarkovProduct` in place of `sequential_sum_product` and testing that the result is fully compatible with `funsor.optimizer.apply_optimizer`, since I think that may be necessary for your problem, but the other stuff is less important.

**Comment by ordabayevy** [comment]
@eb8680 sounds good. Can you point to an example that tests compatibility with `funsor.optimizer.apply_optimizer`?

**Comment by eb8680** [comment]
> Can you point to an example that tests compatibility with funsor.optimizer.apply_optimizer?

See my PR #400 - that should address this point.
