### ISSUE TITLE
Full-featured distribution wrappers

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/funsor#386]
The biggest single issue blocking wider use of Funsor in Pyro and NumPyro right now is the incomplete coverage of distributions.  

At a high level, the goal is to be able to perform all distribution operations that appear in any Pyro or NumPyro model (e.g. sampling and scoring) on Funsors directly, where distribution funsors are obtained from using `to_funsor` to automatically convert distributions to Funsors initially and using `funsor.to_data` to automatically convert the final results back to raw PyTorch/JAX objects.

We have gotten pretty far with the generic wrappers in `funsor.distribution` and `funsor.{jax,torch}.distributions`, but finishing the job and achieving full coverage of `pyro.distributions` remains a challenge because of the large distribution API and number of distributions, many small impedance mismatches and legacy design choices in PyTorch (e.g. the data type of `Bernoulli`), and difficulty of programmatic access and automation (e.g. no generic tool for constructing random valid instances of a distribution given a `batch_shape`).

I've tried to collect the remaining Funsor-specific tasks in this issue so that we can better measure progress toward this goal.  We may also need to do additional work upstream in Pyro, NumPyro or PyTorch distributions.

Transforms and `TransformedDistribution`s (some design discussion in #309):
- [ ] #365 Basic conversion of `TransformedDistribution`s to and from `funsor.Distributions`
- [ ] Near-complete coverage of basic `Transform`s in Pyro and NumPyro
- [ ] Wrappers for `ConditionalTransform`s and `TransformedModule`s
- [ ] Direct TFP `Bijector` wrappers

Other basic distribution modifiers:
- [ ] Near-full coverage of basic distributions (easy enough to implement; the difficulty is testing and fixing PyTorch bugs)
- [ ] Find a workaround for casting issues in `Bernoulli` (#348)
- [ ] Converting `funsor.Independent` to and from `Independent` distributions
- [ ] Some Funsor analogue of `Distribution.expand()`
- [ ] Generic support for sampling via `Funsor.sample()` in `funsor.pyro.FunsorDistribution` - done properly, this may eliminate the need for first-class conjugate distribution implementations in backends, e.g. `DirichletMultinomial`
- [ ] Direct wrapping of TFP distributions in the JAX backend - this would probably involve a new subclass `class TFPDistribution(funsor.distribution.Distribution)` with TFP-specific implementations of `_infer_value_domain` and `_infer_param_domain`

Atomic distribution computations implemented in the backend libraries:
- [ ] Entropy (discussed in #374)
- [ ] KL divergence (discussed in #374)
- [ ] Mean (`TorchDistribution.mean`)
- [ ] Variance (`TorchDistribution.variance`)
- [ ] Conjugate updates (may be unnecessary?)

Test harnesses for distribution wrappers (testing correctness of underlying distribution functionality here is out of scope - we are mostly interested in ensuring that results are converted to Funsors correctly):
- [ ] conversion with `to_funsor` and `to_data`
- [ ] types and shapes
- [ ] densities
- [ ] samplers
- [ ] gradients
- [ ] enumeration (`enumerate_support`)
- [ ] transforms
- [ ] conjugacy
- [ ] deprecate existing, case-by-case tests

**Comment by eb8680** [comment]
> Conversion of TransformedDistributions to and from funsors on the JAX backend (can copy #365)

Note this will be a bit trickier than expected because in NumPyro `Transform.inv` is just a regular method, rather than returning an `_InverseTransform`, which NumPyro does not implement.

**Comment by fehiepsi** [comment]
I will make a PR for that. :)
