### ISSUE TITLE
Implement distribution shape helpers to avoid need for dummy tensors

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#412]
As mentioned in https://github.com/pyro-ppl/funsor/pull/402#discussion_r542716992 we should add distribution methods upstream to perform all needed shape operations.

Currently Funsor's distribution shaping logic uses the pattern of creating fake distributions with dummy tensors to determine distribution event shape and batch shape. As a goal for Funsor use in Pyro 2.0, we should eliminate the need to ever instantiate a dummy tensor, and should eliminate the tensor shape caches.

## Tasks
- [x] #420 decide on shape helper interface
- [x] #420 refactor Funsor to use the new methods instead of fake distributions
- [x] https://github.com/pyro-ppl/pyro/pull/2739 add to Pyro / PyTorch distributions
- [x] https://github.com/pyro-ppl/numpyro/pull/901 add to NumPyro / JAX / TFP distributions

**Comment by eb8680** [comment]
Now that https://github.com/pyro-ppl/pyro/pull/2739 has landed, what's left to do on the Funsor side?

**Comment by fritzo** [comment]
I think it's safe to close this. Possible future tasks include:
- being a little stricter as in #426 (but this is not necessary)
- supporting dependent types via `Value`, which would be required for e.g. `LKJCholesky`
