### ISSUE TITLE
Support for non-funsor arguments to ops

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#489]
This issue tracks changes needed to support non-funsor args as in @ordabayevy's #482, e.g.
```py
ops.sum(Tensor(data), -1, keepdims=True)
# -op-dispatch-> Unary(ops.SumOp(-1, True), Tensor(data))
# -eager-> Tensor(ops.SumOp(-1,True)(data))  # TODO fix batch dimension handling
```

## Plan
Note during the first two refactorings, we may want to try to decouple dispatch tables from the `Op` hierarchy (but that would be a bigger refactoring, possibly beyond the scope of this issue).
- [x] #491 Refactor `Op` so that the dispatch table is in `Op` subclasses, not in instances.
- [x] #490 Demonstrate parametrized ops via `ops.sum(data, dim=None, keepdims=False)`
- [x] #482 Fix batch dimension handling in `Tensor.eager_unary()`
- [x] #482 add more ops, e.g. a richer `ops.sum`, `ops.mean`, etc.

**Comment by eb8680** [comment]
Can this be closed now that #482 is merged?

**Comment by fritzo** [comment]
Yes, thanks for your help @ordabayevy !
