### ISSUE TITLE
Add immutable funsors Dict, Set and use them for funsor data

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#525]
## The problem

Funsors currently store data in immutable structures that are typically either nested tuples or frozensets, e.g. `Subs` converts its dict argument to a nested tuple-of-tuples representing key,value pairs.  These internal data structures complicate funsor traversal algorithms (e.g. `reinterpret`, `ast()`, `get_children()`), since the intermediate non-`Funsor` data structures lack metadata such as `.inputs`, `.output`, `.fresh`, `.bound`.  This complication manifests as extra checks for `isinstance(-, Funsor)` and extra handling to manually traverse funsor data asts.

## Proposed solution

This issue proposes to replace all internal data structure of funsors by additional low-level Pythonic funsors `Tuple`, `Dict`, and `Set`.  Like other more mathy funsors, these data structural funsors implement metadata like `.inputs`, `.output`, substitution via `.__call__()` and reinterpreted construction and hash consing via `type(-).__call__()`.

For example `Subs.subs : Dict`, `Delta.terms : Dict`, etc.

## Remaining questions

1. Should we also implement `Funsor` subclasses for constants `Str` as used as keys? Ideally all terms would be immutable and hash-consed, however `str`s are used so ubiquitously as keys that it may not be worth the performance overhead.  One option would be to instead rely on Python's built-in hash-consing of strings via [sys.intern()](https://docs.python.org/3/library/sys.html#sys.intern) and move metadata elsewhere, as in #526

## Tasks

- [ ] Implement an immutable `Dict` funsor
- [ ] Implement an immutable `Set` funsor
- [ ] Use `Dict` and `Set` internally in other `Funsor`s
- [ ] Simplify `funsor.interpreter`

**Comment by fritzo** [comment]
Closing in favor of #526's `funsor.make(-)` and `funsor.subs(-, **kwargs)`
