### ISSUE TITLE
Move metadata from attributes to a global WeakKeyDictionary?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#526]
## The problem

Funsor computations rely on metadata stored as `Funsor` attributes including `.inputs`, `.output`, `.input_vars`, `.fresh`, `.bound`.  One problem with storing metadata as attributes on objects is that any such metadata is then restricted to funsor-owned custom datatypes, namely subclasses of the base `Funsor` class.  These restrictions make it cumbersome to perform funsor computations on non-`Funsor` immutable data such as tuples or frozensets of `Funsors`.

## Proposed solution

Consider moving all funsor metadata to a new metadata layer, say via a `funsor.metadata(-)` function that looks up an immutable `Metadata` object with attributies `.inputs`, `.output`, `.input_vars`, `.fresh`, `.bound` etc.  All `Metadata` instances are stored in a single global `WeakKeyDictionary` keyed on the immutable data which implements `.__hash__()`.

## Remaining questions

1. Note that this still wouldn't allow reinterpretation of non-Funsor subclass data. See #525 for a complementary refactoring

## Tasks

- [ ] Add a `funsor.metadata(-)` function and `Metadata` class
- [ ] Move `.inputs` and `.output` into `Metadata`
- [ ] Move `.fresh` and `.bound` into `Metadata`
- [ ] Add a `frozendict` type
- [ ] Compute metadata for other non-`Funsor`-subclass types: tuple, frozenset, frozendict
- [ ] Simplify `funsor.interpreter` by using the new metadata
