### ISSUE TITLE
Fix funsor.minipyro and add tests

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#57]
[funsor/minipyro.py](https://github.com/pyro-ppl/funsor/blob/master/funsor/minipyro.py) is currently only a storyboard: it does not function but does serve to demonstrate syntax and computations we'd like to support in funsor.

## Tasks
- [ ] add tests for eager sampling
- [ ] add tests for delayed sampling
- [ ] add tests for `trace`
- [ ] add tests for `replay`
- [ ] add tests for `block`
- [ ] add tests for `pyro.plate`
- [ ] add tests for `log_joint`
- [ ] add tests for `barrier`
- [ ] add tests for `ground`
