### ISSUE TITLE
Support plates and convolution dims in Funsors?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#70]
@eb8680 suggested adding metadata to `Domain` objects or `.input` dicts to declare which inputs are plate indices. This is similar to @jpchen's suggestion of a `Cat` funsor, but would also support cat-broadcasting. From a mathematical perspective, adding funsors with different plate indices would be a direct sum.

I believe the best way to implement this is to first implement correct math in `funsor.minipyro.log_joint` and then to refactor it into `Domain` or `Funsor`.

## Tasks
- [x] #56 sketch plate math in `funsor.minipyro.log_joint`
- [x] #57 fix minipyro and add tests
- [ ] #109 add plate-aware contract/expectation ops
- [ ] Add a funsor `Conv(x, time_dim, curr_dim, next_dim, new_dim)` satisfying
     ```py
     Conv(f, "time", "curr", "next", "curr")(curr=x)
         = f(curr=x(time=arange("time", f.inputs["time"].dtype - 1)),
             next=x(time=arange("time", f.inputs["time"].dtype - 1) + 1))
     ```
- [x] #161 Implement log(time) convolution op following [this paper](https://arxiv.org/abs/1905.13002)
- [x] #292 Generalize `sequential_sum_product` to handle longer time lags
- [ ] Support time dims in `partial_sum_product` (see [convolve-method branch](https://github.com/pyro-ppl/funsor/compare/convolve-method?expand=1))
- [ ] Add a state space example using `Conv` applied to a contiguous stacked nn output

**Comment by eb8680** [comment]
Looking at the Toeplitz and Kronecker `LazyTensor`s in GPyTorch might be helpful too.
