### ISSUE TITLE
Implement recognition of affine transforms

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#72]
To perform full exact inference of Gaussian distributions, we will need some ability to recognize affine transforms. This might either rely on autograd, or could simply pattern match `+`, `*`, and einsum patterns.

## Tasks

- [x] Handle `Binary` and `Variable` patterns #116 
- [x] Rewrite `Normal(Affine, ...)` to an appropriate `Gaussian` #119 
- [x] Handle `Contract` and `einsum` #157 
- [x] Recognize affine funsors including `Contraction` and `Einsum` #249 
- [x] Recognize `GetitemOp` and `ReshapeOp` as a linear transformations #249 
- [x] Rewrite `MultivariateNormal(Affine, ...)` to an appropriate `Gaussian` #245
- [x] Fix `funsor.affine.is_affine()` to be sound but incomplete #282
- [ ] Rewrite `Gaussian(x=affine)` as a `Gaussian`. In three steps: #284, #285, #286

**Comment by fehiepsi** [comment]
Thanks for keeping tracks of those tasks! It is convenient for me to understand what is going on.

**Comment by fritzo** [comment]
@fehiepsi Do you want to try working on the task
> Rewrite `Gaussian(x=affine)` as a `Gaussian`

following the ideas in #245 ? If not, I'm happy to do this part to unblock our first release. If so, it might be a nice intro to Funsor and give us insight into how to incorporate structured Gamma priors in Funsor, generalizing your Pyro PR https://github.com/pyro-ppl/pyro/pull/2025 .

**Comment by fehiepsi** [comment]
Hi @fritzo, could you do it instead? It is better for me to follow-up (though I want to try), given my lacking knowledge of Funsor. I am happy to review and learn from you.

**Comment by fritzo** [comment]
@fehiepsi sounds good, I'll add you as reviewer.
