### ISSUE TITLE
Implement a convolution operation ops.conv

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#86]
Convolution is the basic operation in Gaussian process kernel construction. Convolution only applies to real variables.

## Tasks

- [ ] add `ops.conv`
- [ ] register `Delta`-`Delta`
- [ ] register `Delta`-`Gaussian`
- [ ] register `Gaussian`-`Gaussian`
