### ISSUE TITLE
Implement alpha conversion logic

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#96]
Many places in funsor raise `NotImplementedError` when a bound variable appears free in an expression being substituted. This should be resolved by alpha-converting the binder's expression before substitution (i.e. renaming the bound variable).

@eb8680 suggested handling this uniformly by refactoring e.g. the `Funsor` base class to know about subterms and bound variables. Probably the easiest way to resolve this issue is to refactor first.

## Tasks
- [x] Refactor to let `Funsor` base class know about variable binding and subterms
- [x] Implement alpha conversion once in the `Funsor` base class
- [ ] Make compatible with `funsor.adjoint`
